localCustomFormatsPath: /app/config/cfs
localConfigTemplatesPath: /app/config/templates

sonarr:
  instance1:
    # Set the URL/API Key to your actual instance
    base_url: http://your-sonarr-instance:port
    api_key: !secret SONARR_API_KEY

    include:
      - template: template-sonarr-anime-german
      #- template: dca7e5e9e99c703bcbdaaa471dd40e98 # [German] HD Bluray + WEB
      #  source: TRASH

      # Prefer English/Japanese Dual Audio over English Subs only
      - trash_ids:
          - 418f50b10f1907201b6cfdf881f467b7 # Dual Audio
        assign_scores_to:
          - name: Anime HD
            score: 20

radarr:
  instance1:
    # Set the URL/API Key to your actual instance
    base_url: http://your-radarr-instance:port
    api_key: !secret RADARR_API_KEY

    include:
      - template: template-radarr-anime-german
      #- template: 2b90e905c99490edc7c7a5787443748b # [German] HD Bluray + WEB
      #  source: TRASH
        
      # Prefer English/Japanese Dual Audio over German English only
      - trash_ids:
          - 4a3b087eea2ce012fcc1ce319259a3be # Dual Audio
        assign_scores_to:
          - name: Anime HD
            score: 20

