localCustomFormatsPath: /app/config/cfs
localConfigTemplatesPath: /app/config/templates

sonarr:
  instance1:
    # Set the URL/API Key to your actual instance
    base_url: http://your-sonarr-instance:port
    api_key: !secret SONARR_API_KEY

    include:
      - template: dca7e5e9e99c703bcbdaaa471dd40e98 # [German] HD Bluray + WEB
        source: TRASH

    cloneQualityProfiles:
      - from: "[German] HD Bluray + WEB"
        to: Anime HD

    custom_formats:
      - trash_ids:
        - 133589380b89f8f8394320901529bac1 # Not German or English
        - 15a05bc7c1a36e2b57fd628f8977e2fc # AV1
        - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        # Streaming Services
        - d660701077794679fd59e8bdf4ce3a29 # AMZN
        - f67c9ca88f463a48346062e8ad07713f # ATVP
        - 77a7b25585c18af08f60b1547bb9b4fb # CC
        - 36b72f59f4ea20aad9316f475f2d9fbb # DCU
        - dc5f2bb0e0262155b5fedd0f6c5d2b55 # DSCP
        - 89358767a60cc28783cdc3d0be9388a4 # DSNP
        - 7a235133c87f7da4c8cccceca7e3c7a6 # HBO
        - a880d6abc21e7c16884f3ae393f84179 # HMAX
        - f6cce30f1733d5c8194222a7507909bb # Hulu
        - 0ac24a2a68a9700bcb7eeca8e5cd644c # iT
        - 81d1fbf600e2540cee87f3a23f9d3c1c # MAX
        - d34870697c9db575f17700212167be23 # NF
        - 1656adc6d7bb2c8cca6acfb6592db421 # PCOK
        - c67a75ae4a1715f2bb4d492755ba4195 # PMTP
        - ae58039e1319178e6be73caab5c42166 # SHO
        - 1efe8da11bfd74fbbcd4d8117ddb9213 # STAN
        - 9623c5c9cac8e939c1b9aedd32f640bf # SYFY
        assign_scores_to:
          - name: Anime HD
            score: 0

      - trash_ids:
          - anime-gersub
          - anime-engsub
          - anime-multisub
          - german-subbed
          - lang-not-eng-ger-jpn
          - lang-only-jpn
          - german-anime-groups
          # Anime Streaming Services
          - 3e0b26604165f463f3e8e192261e7284 # CR
          - 1284d18e693de8efe0fe7d6b3e0b9170 # FUNi
          - 44a8ee6403071dd7b8a3a8dd3fe8cb20 # VRV
          - 89358767a60cc28783cdc3d0be9388a4 # DSNP
          - d34870697c9db575f17700212167be23 # NF
          - d660701077794679fd59e8bdf4ce3a29 # AMZN
          - d54cd2bf1326287275b56bccedb72ee2 # ADN
          - 7dd31f3dee6d2ef8eeaa156e23c3857e # B-Global
          - 4c67ff059210182b59cdd41697b8cb08 # Bilibili
          - 570b03b3145a25011bf073274a407259 # HIDIVE
          - a370d974bc7b80374de1d9ba7519760b # ABEMA
        assign_scores_to:
          - name: Anime HD
      
      # Prefer English/Japanese Dual Audio over German Subs only
      - trash_ids:
          - 418f50b10f1907201b6cfdf881f467b7 # Dual Audio
        assign_scores_to:
          - name: Anime HD
            score: 40

radarr:
  instance1:
    # Set the URL/API Key to your actual instance
    base_url: http://your-radarr-instance:port
    api_key: !secret RADARR_API_KEY

    include:
      - template: 2b90e905c99490edc7c7a5787443748b # [German] HD Bluray + WEB
        source: TRASH

    cloneQualityProfiles:
      - from: "[German] HD Bluray + WEB"
        to: Anime HD

    custom_formats:
      - trash_ids:
        - 4eadb75fb23d09dfc0a8e3f687e72287 # Not German or English
        - cae4ca30163749b891686f95532519bd # AV1
        - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
        # Streaming Services
        - b3b3a6ac74ecbd56bcdbefa4799fb9df # AMZN
        - 40e9380490e748672c2522eaaeb692f7 # ATVP
        - 84272245b2988854bfb76a16e60baea5 # DSNP
        - 509e5f41146e278f9eab1ddaceb34515 # HBO
        - 5763d1b0ce84aff3b21038eea8e9b8ad # HMAX
        - 526d445d4c16214309f0fd2b3be18a89 # Hulu
        - e0ec9672be6cac914ffad34a6b077209 # iT
        - 6a061313d22e51e0f25b7cd4dc065233 # MAX
        - 170b1d363bd8516fbf3a3eb05d4faff6 # NF
        - c9fd353f8f5f1baf56dc601c4cb29920 # PCOK
        - e36a0ba1bc902b26ee40818a1d59b8bd # PMTP
        - c2863d2a50c9acad1fb50e53ece60817 # STAN
        assign_scores_to:
          - name: Anime HD
            score: 0

      - trash_ids:
          - anime-gersub
          - anime-engsub
          - anime-multisub
          - german-subbed
          - lang-not-eng-ger-jpn
          - lang-only-jpn
          - german-anime-groups
        assign_scores_to:
          - name: Anime HD
      
      # Prefer English/Japanese Dual Audio over German Subs only
      - trash_ids:
          - 4a3b087eea2ce012fcc1ce319259a3be # Dual Audio
        assign_scores_to:
          - name: Anime HD
            score: 40

